server {
    listen 80 default_server;
    server_name _;
    return 444;
}
server {
    listen 80;
    server_name beautydocs.pl;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }
    location / { return 308 https://beautydocs.pl$request_uri; }
}
